# Generated by Django 3.2.19 on 2023-06-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerreservation',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dinnerreservation',
            name='first_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
